name = "scopehal"
uuid = "ccf5c433-e158-4c88-b032-2e7720eb1497"
authors = ["Pepijn de Vos <pepijndevos@gmail.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
scopehal_jll = "c69b092c-cabd-51ee-983a-b3d58f6c0ce7"
